name: Test App with GitHub Actions
on:
  push:
    branches: [master]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing packages
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: npm install
  test:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - name: Testing using jest after installing packages
      - run: npm test
